language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - cd Demo ; pod install ; cd ..
xcode_workspace: Demo/Demo.xcworkspace
xcode_scheme: Demo
xcode_sdk: iphonesimulator
xctool_args: -destination "platform=iOS Simulator,name=iPhone 4s"
osx_image: xcode7.2
